# ===============================
#  CD Pipeline (Continuous Deployment)
# ===============================
# This workflow runs AFTER the "CI Pipeline" workflow completes successfully.
# It pulls the latest Docker image from Docker Hub, removes the old container,
# and starts a new one with the latest image on the self-hosted runner.
# ===============================

name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]   # Trigger only after the CI pipeline finishes
    types:
      - completed                # Runs when the workflow is marked completed

jobs:
  build:
    runs-on: self-hosted         # Runs on your own self-hosted GitHub runner
    steps:
      # Step 1: Pull the latest Docker image from Docker Hub
      - name: Pull Docker image
        run: sudo docker pull debajyoti23/cicd-1:latest

      # Step 2: Stop & remove any old container named "cicd-1-container"
      # The "|| true" ensures this step won't fail if no container exists
      - name: Delete old Docker container
        run: sudo docker rm -f cicd-1-container || true

      # Step 3: Start a new container from the freshly pulled image
      # -d = run in background
      # -p 8080:8080 = map host port 8080 to container port 8080
      # --name cicd-1-container = give container a fixed name
      - name: Run Docker container
        run: sudo docker run -d -p 8080:8080 --name cicd-1-container debajyoti23/cicd-1:latest
